spring:
  main:
    banner-mode: off
  application:
    name: moshstore
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/moshstore?createDatabaseIfNotExist=true
    username: root
    password: pass
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    #    accessTokenExpiration: 300
    accessTokenExpiration: 30000 # for dev
    refresh-token-expiration: 604800

springdoc:
  swagger-ui:
    # open at http://localhost:8080/docs
    path: /docs
    enabled: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json

payment:
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:3000