spring:
  main:
    banner-mode: off
  application:
    name: moshstore
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refresh-token-expiration: 604800
  profiles:
    active: dev

springdoc:
  swagger-ui:
    # open at http://localhost:8080/docs
    path: /docs
    enabled: true
  api-docs:
    enabled: true
  default-produces-media-type: application/json
  my_api_version: v1.0.0

payment:
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
